"""Seed market_ports with ~100 global ports (idempotent: deletes tenant 'default' rows first)."""
import asyncio
import json

import asyncpg

PORTS = [
    # (name_cn, name_en, un_locode, country, city, type, position, characteristics,
    #  depth_m, max_vessel, cargo_list, modes_list, tput_rank, congestion, carriers, dwell, charges)
    ("洛杉矶", "Los Angeles", "USLAX", "US", "Los Angeles", "seaport",
     "北美西海岸门户，美国最大集装箱港",
     "北美西海岸主要门户港，腹地覆盖加州及美国西部各州。集装箱吞吐全美第一，航线密集。铁路联运直达中西部。适合整柜FCL与拼箱LCL。",
     16.0, "20000+ TEU",
     ["general_cargo", "container", "steel_products", "wire_mesh"],
     ["fcl", "lcl", "rail_intermodal"],
     "high", "high", ["Maersk", "MSC", "CMA CGM", "COSCO", "ONE"], "4-7", "high"),
    ("长滩", "Long Beach", "USLGB", "US", "Los Angeles", "seaport",
     "紧邻洛杉矶港，美国第二大集装箱港",
     "与洛杉矶港构成北美最大港口群。自动化码头比例高，作业效率高。铁路直达美国中西部。",
     16.0, "20000+ TEU",
     ["general_cargo", "container", "steel_products"],
     ["fcl", "rail_intermodal"],
     "high", "high", ["Maersk", "MSC", "CMA CGM", "COSCO", "ONE"], "4-7", "high"),
    ("奥克兰", "Oakland", "USOAK", "US", "San Francisco Bay Area", "seaport",
     "北加州主要门户，替代LA/LB的北部选项",
     "服务北加州及太平洋西北地区。拥堵程度较低，清关较快。适合小批量高频补货。",
     13.5, "14000 TEU",
     ["general_cargo", "container"],
     ["fcl", "lcl", "rail_intermodal"],
     "medium", "medium", ["CMA CGM", "Hapag-Lloyd", "ONE", "ZIM"], "3-5", "medium"),
    ("西雅图", "Seattle", "USSEA", "US", "Seattle", "seaport",
     "美国西北部枢纽，通往阿拉斯加和内陆",
     "服务华盛顿州及太平洋西北地区。与Tacoma组成Northwest Seaport Alliance。铁路覆盖美国中西部。",
     15.0, "18000 TEU",
     ["general_cargo", "container", "timber"],
     ["fcl", "lcl", "rail_intermodal"],
     "medium", "medium", ["Maersk", "MSC", "Hapag-Lloyd", "ONE"], "4-6", "medium"),
    ("塔科马", "Tacoma", "USTIW", "US", "Tacoma", "seaport",
     "西雅图港口群组成部分",
     "与西雅图组成Northwest Seaport Alliance。自动化程度高，适合FCL整柜。",
     15.2, "18000 TEU",
     ["general_cargo", "container"],
     ["fcl", "rail_intermodal"],
     "medium", "medium", ["Maersk", "MSC", "Hapag-Lloyd", "ONE"], "4-6", "medium"),
    ("纽约/新泽西", "New York/New Jersey", "USNYC", "US", "New York", "seaport",
     "美国东海岸最大港，消费市场规模最大",
     "服务美国东北部大都市圈，消费市场规模全美最大。铁路公路联运覆盖纽约、新泽西、宾州。清关较快。",
     14.5, "18000 TEU",
     ["general_cargo", "container", "steel_products"],
     ["fcl", "lcl", "rail_intermodal"],
     "high", "high", ["Maersk", "MSC", "CMA CGM", "Hapag-Lloyd", "ONE", "ZIM"], "4-8", "high"),
    ("萨凡纳", "Savannah", "USSAV", "US", "Savannah", "seaport",
     "美国东海岸增长最快的港口",
     "腹地覆盖美国东南部。码头扩建后吞吐能力提升，清关效率高。铁路直达Atlanta、Charlotte。",
     14.0, "16000 TEU",
     ["general_cargo", "container"],
     ["fcl", "rail_intermodal"],
     "medium", "medium", ["Maersk", "MSC", "CMA CGM", "COSCO", "ONE"], "3-5", "medium"),
    ("休斯顿", "Houston", "USHOU", "US", "Houston", "seaport",
     "美国墨西哥湾门户，能源化工重镇",
     "美国墨西哥湾最大港口。集装箱业务增长迅速，清关便利。铁路覆盖Dallas、Austin。散杂货和项目货能力强。",
     14.0, "16000 TEU",
     ["general_cargo", "container", "project_cargo", "steel_products"],
     ["fcl", "lcl", "break_bulk", "rail_intermodal"],
     "medium", "medium", ["Maersk", "MSC", "CMA CGM", "Hapag-Lloyd", "ZIM"], "4-6", "medium"),
    ("迈阿密", "Miami", "USMIA", "US", "Miami", "seaport",
     "美国通往拉美和加勒比的海上门户",
     "美国通往拉丁美洲和加勒比地区的主要门户。佛罗里达消费市场活跃。",
     11.5, "8000 TEU",
     ["general_cargo", "container"],
     ["fcl", "lcl"],
     "medium", "medium", ["Maersk", "MSC", "CMA CGM", "Crowley"], "3-5", "medium"),
    ("温哥华", "Vancouver", "CAVAN", "CA", "Vancouver", "seaport",
     "加拿大最大港，通往加拿大内陆及美国中西部",
     "加拿大最大的港口。铁路联运覆盖加拿大内陆（Toronto、Montreal、Calgary）及美国中西部。清关效率高。",
     15.5, "20000+ TEU",
     ["general_cargo", "container", "timber", "grain"],
     ["fcl", "lcl", "rail_intermodal"],
     "medium", "medium", ["Maersk", "MSC", "CMA CGM", "COSCO", "ONE", "ZIM"], "4-6", "medium"),
    ("蒙特利尔", "Montreal", "CAMTR", "CA", "Montreal", "seaport",
     "加拿大东部主要门户，服务魁北克和安大略",
     "服务加拿大东部。圣劳伦斯河航道限制船型，主要接卸中型集装箱船。适合连接欧洲和地中海航线。",
     11.0, "8000 TEU",
     ["general_cargo", "container"],
     ["fcl", "lcl"],
     "medium", "medium", ["Maersk", "MSC", "CMA CGM", "Hapag-Lloyd"], "5-7", "medium"),
    ("鲁珀特王子港", "Prince Rupert", "CAPRR", "CA", "Prince Rupert", "seaport",
     "加拿大西海岸深水良港，美加铁路联运枢纽",
     "加拿大西海岸最深的天然良港，不冻港。距亚洲比温哥华近约2天航程。铁路直达美国中西部。",
     17.0, "20000+ TEU",
     ["general_cargo", "container", "grain", "coal"],
     ["fcl", "rail_intermodal"],
     "low", "low", ["Maersk", "MSC", "COSCO", "ONE"], "2-4", "low"),
    ("曼萨尼约", "Manzanillo", "MXZLO", "MX", "Manzanillo", "seaport",
     "墨西哥最大集装箱港，太平洋沿岸枢纽",
     "墨西哥最大的集装箱港，承担墨西哥约40%的海运贸易。连接墨西哥城及中部内陆。",
     14.0, "14000 TEU",
     ["general_cargo", "container", "automotive"],
     ["fcl", "lcl", "rail_intermodal"],
     "medium", "high", ["Maersk", "MSC", "CMA CGM", "Hapag-Lloyd", "ONE"], "5-8", "medium"),
    ("韦拉克鲁斯", "Veracruz", "MXVER", "MX", "Veracruz", "seaport",
     "墨西哥东海岸门户，历史最悠久港口",
     "墨西哥东海岸主要门户。服务墨西哥城及中南部内陆。加勒比和墨西哥湾航线交汇。",
     12.0, "8000 TEU",
     ["general_cargo", "container", "petroleum"],
     ["fcl", "lcl"],
     "medium", "medium", ["Maersk", "MSC", "CMA CGM"], "5-8", "medium"),
    ("拉萨罗卡德纳斯", "Lazaro Cardenas", "MXLZC", "MX", "Lazaro Cardenas", "seaport",
     "墨西哥太平洋深水港，扩建后吞吐提升",
     "墨西哥太平洋沿岸深水港，近年大幅扩建。可接卸超大型集装箱船。铁路直达墨西哥城和美国边境。",
     16.0, "14000 TEU",
     ["general_cargo", "container", "automotive", "steel"],
     ["fcl", "lcl", "rail_intermodal"],
     "medium", "medium", ["MSC", "CMA CGM", "COSCO"], "4-7", "medium"),
    ("汉堡", "Hamburg", "DEHAM", "DE", "Hamburg", "seaport",
     "北欧最大河海港，欧洲第三大集装箱港",
     "北欧最大的河海两用港，欧洲第三大集装箱港。腹地覆盖德国全境及中东欧。铁路公路联运极其发达。",
     15.1, "23000 TEU",
     ["general_cargo", "container", "project_cargo", "steel"],
     ["fcl", "lcl", "rail_intermodal"],
     "high", "medium", ["Maersk", "MSC", "CMA CGM", "Hapag-Lloyd", "ONE", "ZIM"], "3-5", "high"),
    ("不来梅哈芬", "Bremerhaven", "DEBRV", "DE", "Bremerhaven", "seaport",
     "德国纯海港，汽车滚装和集装箱并重",
     "德国主要的纯海港。汽车滚装运输欧洲领先。可接卸超大型集装箱船。清关效率高。",
     15.5, "23000 TEU",
     ["general_cargo", "container", "ro_ro", "automotive"],
     ["fcl", "lcl", "ro_ro"],
     "medium", "low", ["Maersk", "MSC", "CMA CGM", "Hapag-Lloyd", "ONE"], "3-5", "medium"),
    ("威廉港", "Wilhelmshaven", "DEWVN", "DE", "Wilhelmshaven", "seaport",
     "德国唯一深水集装箱港",
     "德国唯一位于外海的深水集装箱港。可全天候接卸20000+ TEU超大型船。水深条件德国最佳。",
     17.5, "23000+ TEU",
     ["general_cargo", "container", "crude_oil"],
     ["fcl", "break_bulk"],
     "low", "low", ["Maersk", "MSC", "CMA CGM"], "3-5", "medium"),
    ("鹿特丹", "Rotterdam", "NLRTM", "NL", "Rotterdam", "seaport",
     "欧洲最大港，全球吞吐量领先",
     "欧洲最大的港口。位于莱茵河-马斯河三角洲，腹地覆盖荷兰、德国、比利时、法国东北部。公铁河联运网络极其发达。欧洲首选门户港。",
     17.0, "24000 TEU",
     ["general_cargo", "container", "project_cargo", "chemicals", "steel"],
     ["fcl", "lcl", "break_bulk", "rail_intermodal", "barge"],
     "high", "medium", ["Maersk", "MSC", "CMA CGM", "Hapag-Lloyd", "ONE", "ZIM", "Evergreen"], "2-4", "high"),
    ("安特卫普", "Antwerp", "BEANR", "BE", "Antwerp", "seaport",
     "欧洲第二大港，化工和集装箱枢纽",
     "欧洲第二大港口，全球领先的化工产品集散中心。腹地覆盖比利时、荷兰南部、德国西部、法国北部。",
     15.5, "20000+ TEU",
     ["general_cargo", "container", "chemicals", "petroleum", "steel"],
     ["fcl", "lcl", "rail_intermodal", "barge"],
     "high", "medium", ["Maersk", "MSC", "CMA CGM", "Hapag-Lloyd", "ONE", "ZIM"], "3-5", "high"),
    ("泽布吕赫", "Zeebrugge", "BEZEE", "BE", "Zeebrugge", "seaport",
     "比利时外海港，滚装和液化气专用",
     "比利时外海港。汽车滚装运输欧洲领先。深水条件好。适合Ro-Ro和特定货类。",
     14.5, "14000 TEU",
     ["general_cargo", "ro_ro", "automotive", "lng"],
     ["ro_ro", "fcl"],
     "medium", "low", ["CMA CGM", "Hapag-Lloyd", "DFDS"], "2-4", "medium"),
    ("勒阿弗尔", "Le Havre", "FRLEH", "FR", "Le Havre", "seaport",
     "法国第一大港，西北欧门户之一",
     "法国最大的集装箱港。塞纳河口外港，腹地覆盖巴黎及法国北部。",
     14.0, "18000 TEU",
     ["general_cargo", "container", "petroleum"],
     ["fcl", "lcl", "rail_intermodal"],
     "medium", "medium", ["Maersk", "MSC", "CMA CGM", "Hapag-Lloyd", "ONE"], "3-5", "medium"),
    ("马赛", "Marseille", "FRMRS", "FR", "Marseille", "seaport",
     "法国地中海门户，南欧枢纽",
     "法国最大的海港。服务法国南部、瑞士、意大利北部。连接北非和中东的重要枢纽。",
     14.5, "16000 TEU",
     ["general_cargo", "container", "petroleum", "chemicals"],
     ["fcl", "lcl", "break_bulk"],
     "medium", "medium", ["CMA CGM", "MSC", "Maersk", "Hapag-Lloyd"], "4-6", "medium"),
    ("费利克斯托", "Felixstowe", "GBFXT", "GB", "Felixstowe", "seaport",
     "英国最大集装箱港",
     "英国最大的集装箱港，承担英国约40%的集装箱贸易。公路铁路联运覆盖伦敦及英格兰中部。",
     14.5, "20000+ TEU",
     ["general_cargo", "container"],
     ["fcl", "lcl", "rail_intermodal"],
     "high", "high", ["Maersk", "MSC", "CMA CGM", "Hapag-Lloyd", "ONE"], "4-7", "high"),
    ("南安普顿", "Southampton", "GBSOU", "GB", "Southampton", "seaport",
     "英国南部主要门户，滚装和集装箱",
     "英格兰南部的主要门户。集装箱和汽车滚装并重。",
     13.0, "16000 TEU",
     ["general_cargo", "container", "ro_ro", "automotive"],
     ["fcl", "lcl", "ro_ro"],
     "medium", "medium", ["Maersk", "MSC", "CMA CGM", "Hapag-Lloyd"], "3-5", "medium"),
    ("伦敦门户港", "London Gateway", "GBLGP", "GB", "London", "seaport",
     "泰晤士河口深水集装箱港",
     "泰晤士河口的深水集装箱港，靠近伦敦消费市场。可接卸大型集装箱船。",
     16.0, "18000 TEU",
     ["general_cargo", "container"],
     ["fcl", "lcl"],
     "medium", "medium", ["CMA CGM", "Hapag-Lloyd", "ONE"], "3-5", "medium"),
    ("利物浦", "Liverpool", "GBLIV", "GB", "Liverpool", "seaport",
     "英国西海岸门户，服务英格兰北部",
     "英国西海岸主要港口，服务英格兰北部和爱尔兰。适合连接北美航线。",
     12.0, "10000 TEU",
     ["general_cargo", "container"],
     ["fcl", "lcl"],
     "medium", "medium", ["CMA CGM", "Hapag-Lloyd", "Stena"], "4-6", "medium"),
    ("瓦伦西亚", "Valencia", "ESVLC", "ES", "Valencia", "seaport",
     "地中海西岸最大港，西班牙第一大港",
     "西班牙最大的港口，地中海西岸最大的集装箱港。腹地覆盖西班牙东部和内陆。",
     16.0, "20000+ TEU",
     ["general_cargo", "container", "automotive", "agriculture"],
     ["fcl", "lcl", "rail_intermodal"],
     "medium", "medium", ["Maersk", "MSC", "CMA CGM", "COSCO", "Hapag-Lloyd", "ONE"], "3-5", "medium"),
    ("巴塞罗那", "Barcelona", "ESBCN", "ES", "Barcelona", "seaport",
     "西班牙第二大港，地中海综合枢纽",
     "西班牙第二大港口。集装箱、散杂货、邮轮并重。服务西班牙东北部及法国南部。",
     16.0, "16000 TEU",
     ["general_cargo", "container", "ro_ro", "chemicals"],
     ["fcl", "lcl", "rail_intermodal"],
     "medium", "medium", ["Maersk", "MSC", "CMA CGM", "Hapag-Lloyd", "ONE"], "3-5", "medium"),
    ("阿尔赫西拉斯", "Algeciras", "ESALG", "ES", "Algeciras", "seaport",
     "地中海和大西洋交汇枢纽，中转大港",
     "位于直布罗陀海峡，地中海和大西洋交汇处的枢纽港。以中转贸易为主。深水条件好。",
     17.0, "20000+ TEU",
     ["general_cargo", "container", "petroleum"],
     ["fcl", "lcl", "transshipment"],
     "medium", "medium", ["Maersk", "MSC", "CMA CGM", "Hapag-Lloyd", "ONE"], "3-5", "medium"),
    ("毕尔巴鄂", "Bilbao", "ESBIO", "ES", "Bilbao", "seaport",
     "西班牙北部港口，散杂货和工业货",
     "西班牙北部主要港口，服务巴斯克工业区。散杂货和工业制成品运输为主。",
     13.5, "8000 TEU",
     ["general_cargo", "steel", "automotive", "machinery"],
     ["break_bulk", "lcl"],
     "medium", "low", ["CMA CGM", "Hapag-Lloyd", "Brittany Ferries"], "3-5", "medium"),
    ("热那亚", "Genoa", "ITGOA", "IT", "Genoa", "seaport",
     "意大利第一大港，地中海北部枢纽",
     "意大利最大的港口。腹地覆盖意大利北部工业区（米兰、都灵）。集装箱、散杂货、石油并重。",
     15.0, "14000 TEU",
     ["general_cargo", "container", "petroleum", "steel"],
     ["fcl", "lcl", "break_bulk"],
     "medium", "medium", ["Maersk", "MSC", "CMA CGM", "Hapag-Lloyd", "ONE"], "4-6", "medium"),
    ("的里雅斯特", "Trieste", "ITTRS", "IT", "Trieste", "seaport",
     "意大利东北部港口，中东欧门户",
     "位于亚得里亚海最深处。是中东欧（奥地利、斯洛伐克、匈牙利）的重要出海口。铁路联运发达。",
     13.0, "8000 TEU",
     ["general_cargo", "container", "petroleum", "chemicals"],
     ["fcl", "lcl", "rail_intermodal"],
     "medium", "low", ["MSC", "CMA CGM", "Hapag-Lloyd"], "4-6", "medium"),
    ("焦亚陶罗", "Gioia Tauro", "ITGIT", "IT", "Gioia Tauro", "seaport",
     "地中海最大中转港之一",
     "地中海最大的中转港之一，位于意大利南部。以集装箱中转为主。深水条件好。",
     18.0, "20000+ TEU",
     ["general_cargo", "container"],
     ["transshipment", "fcl"],
     "medium", "medium", ["MSC", "CMA CGM", "COSCO"], "4-6", "medium"),
    ("拉斯佩齐亚", "La Spezia", "ITSPE", "IT", "La Spezia", "seaport",
     "意大利西北海岸深水港，托斯卡纳门户",
     "意大利西北海岸的深水港，服务托斯卡纳和意大利中部。集装箱吞吐量大。",
     14.0, "14000 TEU",
     ["general_cargo", "container", "naval"],
     ["fcl", "lcl"],
     "medium", "low", ["CMA CGM", "Hapag-Lloyd", "ONE"], "4-6", "medium"),
    ("格但斯克", "Gdansk", "PLGDN", "PL", "Gdansk", "seaport",
     "波兰最大海港，波罗的海枢纽",
     "波兰最大的海港，波罗的海主要枢纽。波罗的海最大集装箱港（Baltic Hub）。腹地覆盖波兰及中东欧。",
     15.0, "18000 TEU",
     ["general_cargo", "container", "coal", "petroleum"],
     ["fcl", "lcl", "rail_intermodal"],
     "medium", "medium", ["Maersk", "MSC", "CMA CGM", "Hapag-Lloyd", "ONE"], "4-6", "medium"),
    ("格丁尼亚", "Gdynia", "PLGDY", "PL", "Gdynia", "seaport",
     "波兰第二大港，集装箱和滚装",
     "波兰第二大港。集装箱和汽车滚装为主。服务波兰北部。",
     11.5, "8000 TEU",
     ["general_cargo", "container", "ro_ro"],
     ["fcl", "lcl", "ro_ro"],
     "medium", "low", ["CMA CGM", "Hapag-Lloyd", "Stena"], "4-6", "medium"),
    ("哥德堡", "Gothenburg", "SEGOT", "SE", "Gothenburg", "seaport",
     "瑞典最大港，斯堪的纳维亚门户",
     "瑞典最大的港口，斯堪的纳维亚地区最大的港口。腹地覆盖瑞典、挪威、丹麦。铁路公路联运发达。",
     15.0, "16000 TEU",
     ["general_cargo", "container", "ro_ro", "automotive", "steel"],
     ["fcl", "lcl", "rail_intermodal", "ro_ro"],
     "medium", "low", ["Maersk", "MSC", "CMA CGM", "DFDS", "Stena"], "3-5", "medium"),
    ("奥胡斯", "Aarhus", "DKAAR", "DK", "Aarhus", "seaport",
     "丹麦最大港，集装箱枢纽",
     "丹麦最大的集装箱港。腹地覆盖丹麦日德兰半岛。集装箱和散杂货并重。",
     11.0, "8000 TEU",
     ["general_cargo", "container", "agriculture"],
     ["fcl", "lcl"],
     "medium", "low", ["Maersk", "CMA CGM", "DFDS"], "2-4", "medium"),
    ("赫尔辛基", "Helsinki", "FIHEL", "FI", "Helsinki", "seaport",
     "芬兰首都港，集装箱和客运",
     "芬兰首都门户。集装箱和客运（轮渡）并重。服务芬兰南部。",
     11.0, "8000 TEU",
     ["general_cargo", "container", "ro_ro"],
     ["fcl", "lcl", "ro_ro"],
     "medium", "low", ["Maersk", "MSC", "DFDS", "Tallink"], "3-5", "medium"),
    ("悉尼", "Sydney", "AUSYD", "AU", "Sydney", "seaport",
     "澳大利亚最大城市门户，集装箱港",
     "澳大利亚最大的城市门户。集装箱吞吐量大。清关效率高。服务新南威尔士州。",
     14.5, "14000 TEU",
     ["general_cargo", "container"],
     ["fcl", "lcl"],
     "medium", "medium", ["Maersk", "MSC", "CMA CGM", "COSCO", "ONE", "Hapag-Lloyd"], "4-7", "high"),
    ("墨尔本", "Melbourne", "AUMEL", "AU", "Melbourne", "seaport",
     "澳大利亚南部枢纽，吞吐量领先",
     "澳大利亚最大的集装箱港之一，服务维多利亚州。吞吐量领先。",
     14.0, "14000 TEU",
     ["general_cargo", "container", "automotive"],
     ["fcl", "lcl", "rail_intermodal"],
     "medium", "medium", ["Maersk", "MSC", "CMA CGM", "COSCO", "ONE", "Hapag-Lloyd"], "4-7", "high"),
    ("布里斯班", "Brisbane", "AUBNE", "AU", "Brisbane", "seaport",
     "澳大利亚东北部门户，服务昆士兰",
     "澳大利亚东北部门户，服务昆士兰州。集装箱和散杂货并重。",
     12.5, "8000 TEU",
     ["general_cargo", "container", "coal", "agriculture"],
     ["fcl", "lcl"],
     "medium", "medium", ["Maersk", "MSC", "CMA CGM", "Hapag-Lloyd", "ONE"], "4-7", "medium"),
    ("弗里曼特尔/珀斯", "Fremantle/Perth", "AUPER", "AU", "Perth", "seaport",
     "澳大利亚西海岸门户",
     "澳大利亚西海岸门户，服务西澳大利亚州。距离亚洲较近。",
     13.5, "10000 TEU",
     ["general_cargo", "container", "iron_ore", "petroleum"],
     ["fcl", "lcl"],
     "medium", "low", ["Maersk", "MSC", "CMA CGM", "Hapag-Lloyd"], "5-8", "medium"),
    ("东京", "Tokyo", "JPTYO", "JP", "Tokyo", "seaport",
     "日本首都圈枢纽，集装箱和客运",
     "日本首都圈的主要港口。集装箱和客运并重。服务日本最大消费市场。",
     12.0, "10000 TEU",
     ["general_cargo", "container", "ro_ro"],
     ["fcl", "lcl", "ro_ro"],
     "medium", "medium", ["NYK", "MOL", "K-Line", "ONE"], "3-5", "high"),
    ("横滨", "Yokohama", "JPYOK", "JP", "Yokohama", "seaport",
     "日本第二大集装箱港",
     "日本第二大集装箱港，紧邻东京。设施完善。服务东京都市圈。",
     13.0, "14000 TEU",
     ["general_cargo", "container", "automotive"],
     ["fcl", "lcl"],
     "medium", "medium", ["NYK", "MOL", "K-Line", "ONE"], "3-5", "high"),
    ("大阪", "Osaka", "JPOSA", "JP", "Osaka", "seaport",
     "关西地区枢纽，日本第三大经济中心",
     "关西地区的主要港口。集装箱和散杂货并重。服务京都、大阪、神户都市圈。",
     12.0, "10000 TEU",
     ["general_cargo", "container", "chemicals"],
     ["fcl", "lcl"],
     "medium", "medium", ["NYK", "MOL", "K-Line", "ONE"], "3-5", "medium"),
    ("神户", "Kobe", "JPUKB", "JP", "Kobe", "seaport",
     "关西重要港口，工业品出口",
     "关西重要港口。集装箱、散杂货、时装出口。服务大阪湾地区。",
     12.0, "10000 TEU",
     ["general_cargo", "container", "steel", "automotive"],
     ["fcl", "lcl"],
     "medium", "medium", ["NYK", "MOL", "K-Line", "ONE"], "3-5", "medium"),
    ("名古屋", "Nagoya", "JPNGO", "JP", "Nagoya", "seaport",
     "日本制造业出口重镇，汽车出口第一",
     "日本最大的汽车出口港。制造业出口重镇（丰田等）。集装箱和汽车滚装为主。",
     12.0, "10000 TEU",
     ["general_cargo", "container", "ro_ro", "automotive", "machinery"],
     ["fcl", "lcl", "ro_ro"],
     "medium", "medium", ["NYK", "MOL", "K-Line", "ONE"], "3-5", "medium"),
    ("博多/福冈", "Hakata/Fukuoka", "JPHKT", "JP", "Fukuoka", "seaport",
     "九州门户，连接韩国和中国",
     "九州地区的主要港口，靠近韩国和中国。连接釜山、上海航线距离短。",
     10.0, "6000 TEU",
     ["general_cargo", "container", "ro_ro"],
     ["fcl", "lcl", "ro_ro"],
     "medium", "medium", ["NYK", "MOL", "K-Line", "Pan Star"], "3-5", "medium"),
    ("釜山", "Busan", "KRPUS", "KR", "Busan", "seaport",
     "韩国最大港，全球中转枢纽前五",
     "韩国最大的港口，全球中转量前五。东北亚枢纽。深水条件好。清关效率高。适合中转和所有货类。",
     17.0, "23000+ TEU",
     ["general_cargo", "container", "automotive", "steel", "petroleum"],
     ["fcl", "lcl", "transshipment", "rail_intermodal"],
     "high", "medium", ["Maersk", "MSC", "CMA CGM", "COSCO", "ONE", "Hapag-Lloyd", "HMM"], "3-5", "medium"),
    ("仁川", "Incheon", "KRINC", "KR", "Incheon", "seaport",
     "韩国首都圈门户，紧邻首尔",
     "韩国首都圈的主要门户，紧邻首尔。服务韩国最大消费市场。",
     12.0, "10000 TEU",
     ["general_cargo", "container", "ro_ro"],
     ["fcl", "lcl", "ro_ro"],
     "medium", "medium", ["CMA CGM", "Hapag-Lloyd", "ONE", "HMM"], "3-5", "medium"),
    ("杰贝阿里", "Jebel Ali", "AEJEA", "AE", "Dubai", "seaport",
     "中东最大枢纽港，全球中转前十",
     "中东最大的枢纽港，全球中转量前十。迪拜门户，自由贸易区政策优惠。清关效率中东最高。适合中转、FCL、LCL、散杂货。",
     17.0, "24000 TEU",
     ["general_cargo", "container", "petroleum", "chemicals", "project_cargo"],
     ["fcl", "lcl", "transshipment", "break_bulk"],
     "high", "low", ["Maersk", "MSC", "CMA CGM", "COSCO", "ONE", "Hapag-Lloyd", "Emirates"], "2-4", "high"),
    ("阿布扎比/哈利法", "Abu Dhabi/Khalifa", "AEAUH", "AE", "Abu Dhabi", "seaport",
     "阿联酋首都深水集装箱港",
     "阿联酋首都的深水集装箱港。 Khalifa Port 设施先进。",
     14.0, "14000 TEU",
     ["general_cargo", "container", "petrochemicals", "aluminum"],
     ["fcl", "lcl"],
     "medium", "low", ["CMA CGM", "Hapag-Lloyd", "MSC"], "3-5", "medium"),
    ("吉达", "Jeddah", "SAJED", "SA", "Jeddah", "seaport",
     "红海门户，沙特最大港",
     "红海最大的港口，沙特最大的海港。连接欧洲、非洲、亚洲。清关效率中等。",
     16.0, "18000 TEU",
     ["general_cargo", "container", "petroleum", "food"],
     ["fcl", "lcl"],
     "high", "high", ["Maersk", "MSC", "CMA CGM", "Hapag-Lloyd", "ONE"], "5-8", "medium"),
    ("达曼", "Dammam", "SADMM", "SA", "Dammam", "seaport",
     "沙特东部工业港，石油出口重镇",
     "沙特东部的主要工业港。石油和石化出口重镇。服务沙特东部省。",
     14.0, "14000 TEU",
     ["general_cargo", "container", "petroleum", "petrochemicals"],
     ["fcl", "lcl"],
     "medium", "medium", ["Maersk", "MSC", "CMA CGM", "Hapag-Lloyd"], "5-8", "medium"),
    ("哈马德", "Hamad", "QAHMD", "QA", "Doha", "seaport",
     "卡塔尔深水港，中东新兴枢纽",
     "卡塔尔的深水港，中东新兴枢纽。近年快速扩建。",
     15.0, "14000 TEU",
     ["general_cargo", "container", "petrochemicals", "lng"],
     ["fcl", "lcl"],
     "medium", "medium", ["Maersk", "MSC", "CMA CGM"], "4-6", "medium"),
    ("舒韦赫", "Shuwaikh", "KWSWK", "KW", "Kuwait City", "seaport",
     "科威特主要商港",
     "科威特的主要商港。集装箱和散杂货并重。",
     10.0, "6000 TEU",
     ["general_cargo", "container", "food", "automotive"],
     ["fcl", "lcl"],
     "medium", "medium", ["Maersk", "MSC", "CMA CGM"], "4-6", "medium"),
    ("苏哈尔", "Sohar", "OMSOH", "OM", "Sohar", "seaport",
     "阿曼深水港，中东新兴枢纽",
     "阿曼的深水港，位于霍尔木兹海峡外。工业和港口自由贸易区。",
     16.0, "14000 TEU",
     ["general_cargo", "container", "petrochemicals", "metals"],
     ["fcl", "lcl"],
     "medium", "low", ["CMA CGM", "Hapag-Lloyd", "MSC"], "3-5", "medium"),
    ("塞拉莱", "Salalah", "OMSLL", "OM", "Salalah", "seaport",
     "阿曼南部枢纽，中转大港",
     "阿曼南部的主要港口，全球中转港之一。深水条件好，位置靠近主要航线。",
     16.0, "14000 TEU",
     ["general_cargo", "container", "petroleum"],
     ["transshipment", "fcl", "lcl"],
     "medium", "low", ["Maersk", "MSC", "CMA CGM"], "3-5", "medium"),
    ("海法", "Haifa", "ILHFA", "IL", "Haifa", "seaport",
     "以色列最大港，地中海东部枢纽",
     "以色列最大的港口，地中海东部枢纽。清关效率高。",
     11.5, "10000 TEU",
     ["general_cargo", "container", "petroleum", "chemicals"],
     ["fcl", "lcl"],
     "medium", "medium", ["CMA CGM", "ZIM", "Hapag-Lloyd"], "3-5", "medium"),
    ("阿什杜德", "Ashdod", "ILASH", "IL", "Ashdod", "seaport",
     "以色列南部港口，服务特拉维夫",
     "以色列南部的主要港口，服务特拉维夫及周边。集装箱为主。",
     11.0, "8000 TEU",
     ["general_cargo", "container"],
     ["fcl", "lcl"],
     "medium", "medium", ["CMA CGM", "ZIM", "Hapag-Lloyd"], "3-5", "medium"),
    ("伊斯坦布尔/安巴利", "Istanbul/Ambarli", "TRIST", "TR", "Istanbul", "seaport",
     "土耳其最大城市门户，欧亚交汇",
     "土耳其最大的城市门户，欧亚交汇处。Ambarli是主要集装箱港区。",
     14.0, "14000 TEU",
     ["general_cargo", "container", "automotive", "food"],
     ["fcl", "lcl"],
     "high", "high", ["Maersk", "MSC", "CMA CGM", "Hapag-Lloyd", "ONE", "Turkon"], "5-8", "medium"),
    ("伊兹密尔", "Izmir", "TRIZM", "TR", "Izmir", "seaport",
     "爱琴海门户，服务土耳其西部",
     "爱琴海的主要门户，服务土耳其西部。",
     12.0, "8000 TEU",
     ["general_cargo", "container", "agriculture", "tobacco"],
     ["fcl", "lcl"],
     "medium", "medium", ["CMA CGM", "Hapag-Lloyd", "MSC"], "4-6", "medium"),
    ("梅尔辛", "Mersin", "TRMER", "TR", "Mersin", "seaport",
     "土耳其南部枢纽，地中海东岸",
     "土耳其南部的主要港口，地中海东岸枢纽。服务土耳其南部和东南部。",
     14.0, "10000 TEU",
     ["general_cargo", "container", "food", "chemicals"],
     ["fcl", "lcl"],
     "medium", "medium", ["CMA CGM", "Hapag-Lloyd", "MSC", "Turkon"], "4-6", "medium"),
    ("那瓦舍瓦", "Nhava Sheva (JNPT)", "INNSA1", "IN", "Mumbai", "seaport",
     "印度最大集装箱港，孟买外港",
     "印度最大的集装箱港，孟买的外港。承担印度约50%的集装箱贸易。清关效率中等。",
     14.0, "16000 TEU",
     ["general_cargo", "container", "petroleum", "chemicals", "food"],
     ["fcl", "lcl", "rail_intermodal"],
     "high", "high", ["Maersk", "MSC", "CMA CGM", "COSCO", "ONE", "Hapag-Lloyd"], "5-10", "medium"),
    ("孟德拉", "Mundra", "INMUN1", "IN", "Mundra", "seaport",
     "印度西海岸私营大港，效率高",
     "印度最大的私营港口。效率高，设施先进。清关效率印度最佳。",
     16.0, "18000 TEU",
     ["general_cargo", "container", "coal", "automotive"],
     ["fcl", "lcl", "rail_intermodal"],
     "medium", "medium", ["Maersk", "MSC", "CMA CGM", "COSCO", "Adani"], "3-6", "medium"),
    ("钦奈", "Chennai", "INMAA", "IN", "Chennai", "seaport",
     "印度东海岸枢纽，南印度门户",
     "印度东海岸的主要枢纽，南印度的门户。集装箱和汽车出口并重。",
     13.0, "10000 TEU",
     ["general_cargo", "container", "automotive"],
     ["fcl", "lcl"],
     "high", "high", ["Maersk", "MSC", "CMA CGM", "COSCO", "ONE"], "5-10", "medium"),
    ("加尔各答", "Kolkata", "INCCU", "IN", "Kolkata", "seaport",
     "印度东部老港，恒河三角洲",
     "印度东部的主要港口，位于恒河三角洲。航道限制船型。",
     8.5, "5000 TEU",
     ["general_cargo", "container", "food", "jute"],
     ["lcl", "break_bulk"],
     "high", "high", ["CMA CGM", "Hapag-Lloyd", "MSC"], "7-12", "medium"),
    ("科钦", "Cochin", "INCOK", "IN", "Kochi", "seaport",
     "印度西南海岸深水港",
     "印度西南海岸的深水港，喀拉拉邦。服务印度南部。",
     13.0, "8000 TEU",
     ["general_cargo", "container", "petroleum", "food"],
     ["fcl", "lcl"],
     "medium", "medium", ["CMA CGM", "MSC", "Hapag-Lloyd"], "5-8", "medium"),
    ("胡志明市/盖梅", "Ho Chi Minh City/Cai Mep", "VNSGN", "VN", "Ho Chi Minh City", "seaport",
     "越南最大门户，湄公河三角洲枢纽",
     "越南最大的港口群。Cai Mep-Thi Vai深水港可接卸大型集装箱船。",
     14.0, "16000 TEU",
     ["general_cargo", "container", "rice", "coffee", "seafood"],
     ["fcl", "lcl", "barge"],
     "medium", "medium", ["Maersk", "MSC", "CMA CGM", "COSCO", "ONE", "Hapag-Lloyd"], "3-6", "medium"),
    ("海防", "Haiphong", "VNHPH", "VN", "Haiphong", "seaport",
     "越南北部枢纽，河内出海门户",
     "越南北部的主要港口，河内的出海门户。",
     9.5, "6000 TEU",
     ["general_cargo", "container", "coal", "food"],
     ["fcl", "lcl"],
     "medium", "medium", ["Maersk", "MSC", "CMA CGM", "COSCO", "ONE"], "3-6", "medium"),
    ("林查班", "Laem Chabang", "THLCH", "TH", "Chonburi", "seaport",
     "泰国最大深水港，曼谷外港",
     "泰国最大的深水港，曼谷的外港。承担泰国约80%的集装箱贸易。深水条件好。",
     14.0, "16000 TEU",
     ["general_cargo", "container", "automotive", "petrochemicals", "food"],
     ["fcl", "lcl", "rail_intermodal"],
     "medium", "medium", ["Maersk", "MSC", "CMA CGM", "COSCO", "ONE", "Hapag-Lloyd"], "3-6", "medium"),
    ("曼谷", "Bangkok", "THBKK", "TH", "Bangkok", "seaport",
     "泰国首都河港，湄南河沿岸",
     "泰国首都的河港，湄南河沿岸。航道限制船型。",
     8.5, "5000 TEU",
     ["general_cargo", "container", "food", "rice"],
     ["lcl", "barge"],
     "medium", "high", ["CMA CGM", "Hapag-Lloyd", "RCL"], "4-7", "medium"),
    ("巴生", "Port Klang", "MYPKG", "MY", "Klang", "seaport",
     "马来西亚最大港，东南亚枢纽",
     "马来西亚最大的港口，东南亚主要枢纽。承担马来西亚约70%的海运贸易。深水条件好。",
     15.5, "18000 TEU",
     ["general_cargo", "container", "palm_oil", "electronics"],
     ["fcl", "lcl", "transshipment"],
     "medium", "medium", ["Maersk", "MSC", "CMA CGM", "COSCO", "ONE", "Hapag-Lloyd"], "3-5", "medium"),
    ("槟城", "Penang", "MYPEN", "MY", "Penang", "seaport",
     "马来西亚北部电子工业港",
     "马来西亚北部的主要港口，槟城电子工业基地。服务马来西亚北部。",
     11.0, "8000 TEU",
     ["general_cargo", "container", "electronics", "food"],
     ["fcl", "lcl"],
     "medium", "medium", ["Maersk", "MSC", "CMA CGM", "ONE"], "3-5", "medium"),
    ("柔佛/巴西古当", "Johor (Pasir Gudang)", "MYJHB", "MY", "Johor Bahru", "seaport",
     "马来西亚南部工业港，紧邻新加坡",
     "马来西亚南部的工业港，紧邻新加坡。散杂货和工业货为主。",
     10.0, "6000 TEU",
     ["general_cargo", "break_bulk", "petrochemicals"],
     ["break_bulk", "lcl"],
     "medium", "medium", ["CMA CGM", "Hapag-Lloyd"], "3-5", "medium"),
    ("新加坡", "Singapore", "SGSIN", "SG", "Singapore", "seaport",
     "全球中转第一，效率最高",
     "全球中转量第一的港口。效率极高，几乎所有航线都有挂靠。清关速度全球领先。首选亚洲中转港。",
     17.0, "24000 TEU",
     ["general_cargo", "container", "petroleum", "chemicals", "project_cargo"],
     ["fcl", "lcl", "transshipment", "break_bulk"],
     "high", "low", ["Maersk", "MSC", "CMA CGM", "COSCO", "ONE", "Hapag-Lloyd", "Evergreen", "OOCL", "Yang Ming"], "2-3", "high"),
    ("雅加达/丹戎不碌", "Jakarta/Tanjung Priok", "IDJKT", "ID", "Jakarta", "seaport",
     "印尼最大港，爪哇岛门户",
     "印度尼西亚最大的港口，爪哇岛的门户。承担印尼约60%的海运贸易。",
     11.0, "10000 TEU",
     ["general_cargo", "container", "food", "coal", "petroleum"],
     ["fcl", "lcl"],
     "high", "high", ["Maersk", "MSC", "CMA CGM", "COSCO", "ONE", "Hapag-Lloyd"], "5-9", "medium"),
    ("泗水", "Surabaya", "IDSUB", "ID", "Surabaya", "seaport",
     "印尼第二大城市门户，东爪哇枢纽",
     "印尼第二大城市的主要港口，东爪哇的枢纽。",
     10.5, "8000 TEU",
     ["general_cargo", "container", "food", "tobacco"],
     ["fcl", "lcl"],
     "medium", "medium", ["Maersk", "MSC", "CMA CGM", "ONE"], "5-8", "medium"),
    ("勿拉湾", "Belawan", "IDBLW", "ID", "Medan", "seaport",
     "苏门答腊门户，服务印尼西部",
     "苏门答腊岛的主要门户，服务印尼西部。",
     8.5, "5000 TEU",
     ["general_cargo", "container", "palm_oil", "rubber"],
     ["lcl", "break_bulk"],
     "medium", "medium", ["CMA CGM", "Hapag-Lloyd"], "5-8", "medium"),
    ("马尼拉", "Manila", "PHMNL", "PH", "Manila", "seaport",
     "菲律宾首都门户，吕宋岛枢纽",
     "菲律宾首都的主要门户，吕宋岛的枢纽。承担菲律宾约70%的海运贸易。",
     10.5, "8000 TEU",
     ["general_cargo", "container", "electronics", "food"],
     ["fcl", "lcl"],
     "high", "high", ["Maersk", "MSC", "CMA CGM", "COSCO", "ONE", "Hapag-Lloyd"], "5-9", "medium"),
    ("宿务", "Cebu", "PHCEB", "PH", "Cebu", "seaport",
     "菲律宾中部枢纽，米沙鄢门户",
     "菲律宾中部的主要枢纽，米沙鄢群岛的门户。",
     9.0, "5000 TEU",
     ["general_cargo", "container", "food", "coconut"],
     ["lcl", "break_bulk"],
     "medium", "medium", ["CMA CGM", "Hapag-Lloyd", "2GO"], "5-8", "medium"),
    ("桑托斯", "Santos", "BRSSZ", "BR", "Santos", "seaport",
     "南美最大集装箱港，圣保罗外港",
     "南美洲最大的集装箱港，圣保罗的外港。承担巴西约40%的海运贸易。",
     14.0, "14000 TEU",
     ["general_cargo", "container", "coffee", "soybean", "sugar", "automotive"],
     ["fcl", "lcl"],
     "high", "high", ["Maersk", "MSC", "CMA CGM", "Hapag-Lloyd", "ONE", "ZIM"], "5-10", "medium"),
    ("里约热内卢", "Rio de Janeiro", "BRRIO", "BR", "Rio de Janeiro", "seaport",
     "巴西第二大城市门户",
     "巴西第二大城市的主要门户。服务里约及周边。",
     12.0, "8000 TEU",
     ["general_cargo", "container", "petroleum", "iron_ore"],
     ["fcl", "lcl"],
     "medium", "medium", ["Maersk", "MSC", "CMA CGM"], "5-9", "medium"),
    ("巴拉那瓜", "Paranagua", "BRPNG", "BR", "Paranagua", "seaport",
     "巴西南部大豆出口港",
     "巴西南部的主要港口，大豆出口港。",
     12.0, "6000 TEU",
     ["general_cargo", "container", "soybean", "food"],
     ["break_bulk", "lcl"],
     "medium", "medium", ["CMA CGM", "Hapag-Lloyd", "MSC"], "5-9", "medium"),
    ("布宜诺斯艾利斯", "Buenos Aires", "ARBUE", "AR", "Buenos Aires", "seaport",
     "阿根廷首都门户，拉普拉塔河口",
     "阿根廷首都的主要门户，位于拉普拉塔河口。承担阿根廷约60%的海运贸易。",
     10.5, "8000 TEU",
     ["general_cargo", "container", "food", "soybean", "wheat"],
     ["fcl", "lcl"],
     "medium", "high", ["Maersk", "MSC", "CMA CGM", "Hapag-Lloyd"], "7-12", "medium"),
    ("瓦尔帕莱索", "Valparaiso", "CLVAP", "CL", "Valparaiso", "seaport",
     "智利主要门户，太平洋东岸枢纽",
     "智利的主要门户，太平洋东岸的枢纽。承担智利约50%的海运贸易。",
     11.5, "8000 TEU",
     ["general_cargo", "container", "fruit", "wine", "copper"],
     ["fcl", "lcl"],
     "medium", "medium", ["Maersk", "MSC", "CMA CGM", "Hapag-Lloyd", "ONE", "Hamburg Sud"], "5-9", "medium"),
    ("圣安东尼奥", "San Antonio", "CLSAI", "CL", "San Antonio", "seaport",
     "智利中部港口，瓦尔帕莱索替代",
     "智利中部的主要港口，瓦尔帕莱索的替代选项。集装箱为主。",
     11.5, "10000 TEU",
     ["general_cargo", "container", "fruit"],
     ["fcl", "lcl"],
     "medium", "medium", ["Maersk", "MSC", "CMA CGM", "Hapag-Lloyd"], "5-9", "medium"),
    ("卡亚俄", "Callao", "PECLL", "PE", "Callao", "seaport",
     "秘鲁唯一大港，利马外港",
     "秘鲁最大的港口，利马的外港。承担秘鲁约70%的海运贸易。",
     11.0, "8000 TEU",
     ["general_cargo", "container", "fishmeal", "copper", "food"],
     ["fcl", "lcl"],
     "medium", "medium", ["Maersk", "MSC", "CMA CGM", "Hapag-Lloyd"], "5-9", "medium"),
    ("布埃纳文图拉", "Buenaventura", "COBUN", "CO", "Buenaventura", "seaport",
     "哥伦比亚太平洋门户",
     "哥伦比亚太平洋岸的主要门户。承担哥伦比亚约60%的海运贸易。",
     10.5, "6000 TEU",
     ["general_cargo", "container", "coffee", "banana", "flower"],
     ["fcl", "lcl"],
     "medium", "high", ["Maersk", "MSC", "CMA CGM", "Hapag-Lloyd"], "5-10", "medium"),
    ("科隆", "Colon", "PAPCO", "PA", "Colon", "seaport",
     "巴拿马加勒比侧枢纽，科隆自由区",
     "巴拿马加勒比海侧的主要枢纽，科隆自由贸易区。连接大西洋和太平洋。",
     12.0, "10000 TEU",
     ["general_cargo", "container"],
     ["transshipment", "fcl", "lcl"],
     "medium", "medium", ["Maersk", "MSC", "CMA CGM", "Hapag-Lloyd"], "4-7", "medium"),
    ("巴尔博亚", "Panama City/Balboa", "PAPAN", "PA", "Panama City", "seaport",
     "巴拿马太平洋侧门户，运河入口",
     "巴拿马太平洋侧的主要门户，巴拿马运河太平洋入口。",
     11.5, "8000 TEU",
     ["general_cargo", "container"],
     ["transshipment", "fcl", "lcl"],
     "medium", "medium", ["Maersk", "MSC", "CMA CGM", "Hapag-Lloyd"], "4-7", "medium"),
    ("德班", "Durban", "ZADUR", "ZA", "Durban", "seaport",
     "非洲最大集装箱港，南部非洲枢纽",
     "非洲最大的集装箱港，南部非洲的主要枢纽。承担南非约60%的海运贸易。",
     12.5, "10000 TEU",
     ["general_cargo", "container", "coal", "automotive", "food"],
     ["fcl", "lcl"],
     "medium", "high", ["Maersk", "MSC", "CMA CGM", "COSCO", "ONE", "Hapag-Lloyd"], "5-9", "medium"),
    ("开普敦", "Cape Town", "ZACPT", "ZA", "Cape Town", "seaport",
     "南非立法首都门户，西开普枢纽",
     "南非立法首都的门户。葡萄酒和水果出口港。",
     10.5, "6000 TEU",
     ["general_cargo", "container", "wine", "fruit", "fish"],
     ["fcl", "lcl"],
     "medium", "medium", ["Maersk", "MSC", "CMA CGM"], "6-10", "medium"),
    ("亚历山大", "Alexandria", "EGALY", "EG", "Alexandria", "seaport",
     "埃及最大港，地中海枢纽",
     "埃及最大的港口，地中海的主要枢纽。承担埃及约55%的海运贸易。",
     10.5, "8000 TEU",
     ["general_cargo", "container", "food", "cotton", "petroleum"],
     ["fcl", "lcl"],
     "medium", "high", ["Maersk", "MSC", "CMA CGM", "Hapag-Lloyd"], "5-9", "medium"),
    ("塞得港", "Port Said", "EGPSD", "EG", "Port Said", "seaport",
     "苏伊士运河入口，全球中转枢纽",
     "苏伊士运河地中海入口，全球中转枢纽。连接欧洲、亚洲、非洲。深水条件好。",
     15.0, "20000+ TEU",
     ["general_cargo", "container"],
     ["transshipment", "fcl", "lcl"],
     "medium", "medium", ["Maersk", "MSC", "CMA CGM", "COSCO", "ONE", "Hapag-Lloyd"], "4-7", "medium"),
    ("拉各斯/阿帕帕", "Lagos/Apapa", "NGAPP", "NG", "Lagos", "seaport",
     "西非最大港，尼日利亚经济中心",
     "西非最大的港口，尼日利亚的经济中心。承担尼日利亚约70%的海运贸易。清关效率较低，拥堵常见。",
     9.5, "6000 TEU",
     ["general_cargo", "container", "petroleum", "food"],
     ["fcl", "lcl"],
     "high", "high", ["Maersk", "MSC", "CMA CGM", "Hapag-Lloyd", "ZIM"], "10-20", "medium"),
    ("蒙巴萨", "Mombasa", "KEMBA", "KE", "Mombasa", "seaport",
     "东非最大港，肯尼亚及内陆枢纽",
     "东非最大的港口，肯尼亚及乌干达、卢旺达等内陆国的主要出海口。",
     10.5, "8000 TEU",
     ["general_cargo", "container", "food", "tea", "coffee"],
     ["fcl", "lcl"],
     "medium", "high", ["Maersk", "MSC", "CMA CGM", "Hapag-Lloyd"], "7-14", "medium"),
    ("丹吉尔地中海", "Tanger Med", "MAPTM", "MA", "Tangier", "seaport",
     "北非最大港，地中海-大西洋枢纽",
     "北非最大的港口，地中海和大西洋交汇处的枢纽。深水条件好，可接卸超大型船。清关效率较高。",
     16.0, "20000+ TEU",
     ["general_cargo", "container", "automotive"],
     ["fcl", "lcl", "transshipment"],
     "medium", "low", ["Maersk", "MSC", "CMA CGM", "Hapag-Lloyd", "ONE"], "3-5", "medium"),
    ("卡萨布兰卡", "Casablanca", "MACAS", "MA", "Casablanca", "seaport",
     "摩洛哥经济中心门户",
     "摩洛哥的经济中心门户。服务摩洛哥西部。",
     10.0, "6000 TEU",
     ["general_cargo", "container", "phosphate", "food"],
     ["fcl", "lcl"],
     "medium", "medium", ["CMA CGM", "Hapag-Lloyd", "MSC"], "4-7", "medium"),
    ("奥克兰", "Auckland", "NZAKL", "NZ", "Auckland", "seaport",
     "新西兰最大城市门户",
     "新西兰最大的城市门户。承担新西兰约40%的海运贸易。清关效率高。",
     11.0, "8000 TEU",
     ["general_cargo", "container", "dairy", "food"],
     ["fcl", "lcl"],
     "medium", "low", ["Maersk", "MSC", "CMA CGM", "COSCO", "ONE", "Hapag-Lloyd"], "3-5", "medium"),
    ("利特尔顿", "Lyttelton", "NZLYT", "NZ", "Christchurch", "seaport",
     "南岛主要门户，基督城外港",
     "新西兰南岛的主要门户，基督城的外港。服务南岛。",
     9.5, "5000 TEU",
     ["general_cargo", "container", "food", "dairy"],
     ["fcl", "lcl"],
     "medium", "low", ["CMA CGM", "Hapag-Lloyd", "MSC"], "4-6", "medium"),
]

DSN = "postgresql://neondb_owner:npg_FU7X4gicMjkn@ep-small-brook-b54t5318-pooler.c-7.us-east-2.aws.neon.tech/neondb"


async def main():
    conn = await asyncpg.connect(DSN)
    await conn.execute("DELETE FROM market_ports WHERE tenant_id='default'")
    inserted = 0
    rank_map = {"high": 5, "medium": 3, "low": 1}

    def dwell_mid(v):
        parts = str(v).replace("–", "-").split("-")
        try:
            return (float(parts[0]) + float(parts[-1])) / 2
        except ValueError:
            return None

    for p in PORTS:
        await conn.execute(
            """INSERT INTO market_ports
               (tenant_id, name_cn, name_en, un_locode, country_code, city, port_type,
                position_desc, characteristics, berth_depth_m, max_vessel_size,
                suitable_cargo, suitable_shipping_modes, throughput_rank, congestion_level,
                major_carriers, avg_dwell_days, port_charges_level, source, created_at, updated_at)
               VALUES ('default',$1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11::jsonb,$12::jsonb,$13,$14,$15::jsonb,$16,$17,'manual',NOW(),NOW())""",
            p[0], p[1], p[2], p[3], p[4], p[5], p[6], p[7], p[8], p[9],
            json.dumps(p[10], ensure_ascii=False),
            json.dumps(p[11], ensure_ascii=False),
            rank_map.get(p[12], 3), p[13], json.dumps(p[14], ensure_ascii=False),
            dwell_mid(p[15]), p[16],
        )
        inserted += 1
    print(f"inserted {inserted} ports")
    await conn.close()


if __name__ == "__main__":
    asyncio.run(main())
