"""int_r3_quoting_domain

Revision ID: 46708631974a
Revises: 202605030002
Create Date: 2026-05-03 10:34:14.096849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '46708631974a'
down_revision: Union[str, None] = '202605030002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_cost_items',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.Column('customer_id', sa.Text(), nullable=False),
    sa.Column('product_category', sa.Text(), nullable=False),
    sa.Column('product_spec_id', sa.BigInteger(), nullable=True),
    sa.Column('product_spec_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('spec_hash', sa.Text(), nullable=False),
    sa.Column('cost_type', sa.Text(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.Text(), nullable=False),
    sa.Column('unit', sa.Text(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cost_items_lookup', 'customer_cost_items', ['tenant_id', 'customer_id', 'spec_hash'], unique=False)
    op.create_table('customer_freight_rates',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.Column('customer_id', sa.Text(), nullable=False),
    sa.Column('carrier', sa.Text(), nullable=False),
    sa.Column('province', sa.Text(), nullable=False),
    sa.Column('formula_type', sa.Text(), nullable=False),
    sa.Column('base_fee', sa.Float(), nullable=True),
    sa.Column('threshold_kg', sa.Float(), nullable=True),
    sa.Column('per_kg_after_threshold', sa.Float(), nullable=True),
    sa.Column('min_weight_kg', sa.Float(), nullable=True),
    sa.Column('fixed_fee', sa.Float(), nullable=True),
    sa.Column('effective_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_freight_lookup', 'customer_freight_rates', ['tenant_id', 'customer_id', 'province'], unique=False)
    op.create_table('customer_pricing_profiles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.Column('customer_id', sa.Text(), nullable=False),
    sa.Column('product_category', sa.Text(), nullable=False),
    sa.Column('profile_name', sa.Text(), nullable=False),
    sa.Column('low_margin_rate', sa.Float(), nullable=False),
    sa.Column('standard_margin_rate', sa.Float(), nullable=False),
    sa.Column('high_margin_rate', sa.Float(), nullable=False),
    sa.Column('tax_rate', sa.Float(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pricing_profile_lookup', 'customer_pricing_profiles', ['tenant_id', 'customer_id', 'product_category'], unique=False)
    op.create_table('customer_sale_price_items',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.Column('customer_id', sa.Text(), nullable=False),
    sa.Column('product_category', sa.Text(), nullable=False),
    sa.Column('product_spec_id', sa.BigInteger(), nullable=True),
    sa.Column('product_spec_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('spec_hash', sa.Text(), nullable=False),
    sa.Column('sale_price_type', sa.Text(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.Text(), nullable=False),
    sa.Column('unit', sa.Text(), nullable=False),
    sa.Column('min_quantity', sa.Integer(), nullable=True),
    sa.Column('effective_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sale_price_lookup', 'customer_sale_price_items', ['tenant_id', 'customer_id', 'spec_hash'], unique=False)
    op.create_table('product_specs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('product_category', sa.Text(), nullable=False),
    sa.Column('product_type', sa.Text(), nullable=True),
    sa.Column('wire_diameter', sa.Text(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('mesh_width', sa.Float(), nullable=True),
    sa.Column('mesh_spec', sa.Text(), nullable=True),
    sa.Column('roll_length', sa.Float(), nullable=True),
    sa.Column('bundle_size', sa.Integer(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('spec_hash', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('spec_hash')
    )
    op.create_index('idx_product_specs_category', 'product_specs', ['product_category', 'product_type'], unique=False)
    op.drop_index(op.f('idx_events_session'), table_name='events', postgresql_where='(session_id IS NOT NULL)')
    op.drop_index(op.f('idx_events_tenant_type_time'), table_name='events')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_events_tenant_type_time'), 'events', ['tenant_id', 'event_type', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_events_session'), 'events', ['session_id'], unique=False, postgresql_where='(session_id IS NOT NULL)')
    op.drop_index('idx_product_specs_category', table_name='product_specs')
    op.drop_table('product_specs')
    op.drop_index('idx_sale_price_lookup', table_name='customer_sale_price_items')
    op.drop_table('customer_sale_price_items')
    op.drop_index('idx_pricing_profile_lookup', table_name='customer_pricing_profiles')
    op.drop_table('customer_pricing_profiles')
    op.drop_index('idx_freight_lookup', table_name='customer_freight_rates')
    op.drop_table('customer_freight_rates')
    op.drop_index('idx_cost_items_lookup', table_name='customer_cost_items')
    op.drop_table('customer_cost_items')
    # ### end Alembic commands ###
