"""intel_workstation_v2_remaining_tables

Revision ID: 60642caa63f5
Revises: f82ac951b473
Create Date: 2026-09-18 15:58:39.087180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '60642caa63f5'
down_revision: Union[str, None] = 'f82ac951b473'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intel_data_channels',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('channel_type', sa.Text(), nullable=False),
    sa.Column('tier', sa.Text(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_intel_channels_tenant', 'intel_data_channels', ['tenant_id', 'channel_type'], unique=False)
    op.create_table('intel_sources',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('source_type', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('api_key', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_intel_sources_tenant', 'intel_sources', ['tenant_id', 'source_type'], unique=False)
    op.create_table('intel_trade_stats',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.Column('hs_code', sa.Text(), nullable=False),
    sa.Column('period', sa.Text(), nullable=False),
    sa.Column('reporter_country', sa.Text(), nullable=True),
    sa.Column('partner_country', sa.Text(), nullable=False),
    sa.Column('trade_flow', sa.Text(), nullable=False),
    sa.Column('qty', sa.Numeric(), nullable=True),
    sa.Column('qty_unit', sa.Text(), nullable=True),
    sa.Column('value_usd', sa.Numeric(), nullable=True),
    sa.Column('source_channel', sa.Text(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_intel_trade_stats_lookup', 'intel_trade_stats', ['tenant_id', 'hs_code', 'period', 'partner_country'], unique=False)
    op.create_table('intel_adapter_runs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.Column('source_id', sa.BigInteger(), nullable=True),
    sa.Column('channel_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('items_processed', sa.Integer(), nullable=False),
    sa.Column('items_inserted', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('run_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['intel_data_channels.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['intel_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_intel_adapter_runs_tenant', 'intel_adapter_runs', ['tenant_id', 'started_at'], unique=False)
    op.create_table('intel_keyword_rules',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=True),
    sa.Column('keyword', sa.Text(), nullable=False),
    sa.Column('lang', sa.Text(), nullable=False),
    sa.Column('match_type', sa.Text(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['intel_product_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_intel_keywords_tenant', 'intel_keyword_rules', ['tenant_id', 'category_id', 'lang'], unique=False)
    op.create_table('intel_matches',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.Column('match_type', sa.Text(), nullable=False),
    sa.Column('ref_id', sa.BigInteger(), nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=True),
    sa.Column('matched_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('relevance', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('follow_notes', sa.Text(), nullable=True),
    sa.Column('followed_by', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['intel_product_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_intel_matches_tenant', 'intel_matches', ['tenant_id', 'match_type', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_intel_matches_tenant', table_name='intel_matches')
    op.drop_table('intel_matches')
    op.drop_index('idx_intel_keywords_tenant', table_name='intel_keyword_rules')
    op.drop_table('intel_keyword_rules')
    op.drop_index('idx_intel_adapter_runs_tenant', table_name='intel_adapter_runs')
    op.drop_table('intel_adapter_runs')
    op.drop_index('idx_intel_trade_stats_lookup', table_name='intel_trade_stats')
    op.drop_table('intel_trade_stats')
    op.drop_index('idx_intel_sources_tenant', table_name='intel_sources')
    op.drop_table('intel_sources')
    op.drop_index('idx_intel_channels_tenant', table_name='intel_data_channels')
    op.drop_table('intel_data_channels')
    # ### end Alembic commands ###
