"""intel_workstation_v1

Revision ID: f82ac951b473
Revises: 202605220001
Create Date: 2026-09-18 15:47:50.585688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f82ac951b473'
down_revision: Union[str, None] = '202605220001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_capabilities',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.Column('customer_id', sa.Text(), nullable=False),
    sa.Column('customer_name', sa.Text(), nullable=False),
    sa.Column('product_category', sa.Text(), nullable=False),
    sa.Column('spec_constraints', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('effective_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_capabilities_lookup', 'customer_capabilities', ['customer_id', 'product_category'], unique=False)
    op.create_index('idx_capabilities_tenant', 'customer_capabilities', ['tenant_id', 'customer_id'], unique=False)
    op.create_index(op.f('ix_customer_capabilities_tenant_id'), 'customer_capabilities', ['tenant_id'], unique=False)
    op.create_table('customer_cost_items',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.Column('customer_id', sa.Text(), nullable=False),
    sa.Column('product_category', sa.Text(), nullable=False),
    sa.Column('product_spec_id', sa.BigInteger(), nullable=True),
    sa.Column('product_spec_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('spec_hash', sa.Text(), nullable=False),
    sa.Column('cost_type', sa.Text(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.Text(), nullable=False),
    sa.Column('unit', sa.Text(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cost_items_lookup', 'customer_cost_items', ['tenant_id', 'customer_id', 'spec_hash'], unique=False)
    op.create_table('customer_freight_rates',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.Column('customer_id', sa.Text(), nullable=False),
    sa.Column('carrier', sa.Text(), nullable=False),
    sa.Column('province', sa.Text(), nullable=False),
    sa.Column('formula_type', sa.Text(), nullable=False),
    sa.Column('base_fee', sa.Float(), nullable=True),
    sa.Column('threshold_kg', sa.Float(), nullable=True),
    sa.Column('per_kg_after_threshold', sa.Float(), nullable=True),
    sa.Column('min_weight_kg', sa.Float(), nullable=True),
    sa.Column('fixed_fee', sa.Float(), nullable=True),
    sa.Column('effective_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_freight_lookup', 'customer_freight_rates', ['tenant_id', 'customer_id', 'province'], unique=False)
    op.create_table('customer_pricing_profiles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.Column('customer_id', sa.Text(), nullable=False),
    sa.Column('product_category', sa.Text(), nullable=False),
    sa.Column('profile_name', sa.Text(), nullable=False),
    sa.Column('low_margin_rate', sa.Float(), nullable=False),
    sa.Column('standard_margin_rate', sa.Float(), nullable=False),
    sa.Column('high_margin_rate', sa.Float(), nullable=False),
    sa.Column('tax_rate', sa.Float(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pricing_profile_lookup', 'customer_pricing_profiles', ['tenant_id', 'customer_id', 'product_category'], unique=False)
    op.create_table('customer_sale_price_items',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.Column('customer_id', sa.Text(), nullable=False),
    sa.Column('product_category', sa.Text(), nullable=False),
    sa.Column('product_spec_id', sa.BigInteger(), nullable=True),
    sa.Column('product_spec_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('spec_hash', sa.Text(), nullable=False),
    sa.Column('sale_price_type', sa.Text(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.Text(), nullable=False),
    sa.Column('unit', sa.Text(), nullable=False),
    sa.Column('min_quantity', sa.Integer(), nullable=True),
    sa.Column('effective_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sale_price_lookup', 'customer_sale_price_items', ['tenant_id', 'customer_id', 'spec_hash'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.Column('code', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('plan', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('idx_customers_code', 'customers', ['code'], unique=False)
    op.create_index('idx_customers_tenant', 'customers', ['tenant_id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('event_source', sa.Text(), nullable=False),
    sa.Column('actor_id', sa.Text(), nullable=True),
    sa.Column('session_id', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('trace_id', sa.Text(), nullable=True),
    sa.Column('sampled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events_archive_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('minio_path', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('industry_templates',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('industry_code', sa.Text(), nullable=False),
    sa.Column('template_type', sa.Text(), nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=True),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('snapshot_version', sa.Integer(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_it_industry', 'industry_templates', ['industry_code', 'is_active'], unique=False)
    op.create_table('intel_entities',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('name_raw', sa.Text(), nullable=False),
    sa.Column('name_norm', sa.Text(), nullable=True),
    sa.Column('country', sa.Text(), nullable=True),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('contact_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('source_channel', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_intel_entities_name', 'intel_entities', ['tenant_id', 'name_norm'], unique=False)
    op.create_index('idx_intel_entities_tenant', 'intel_entities', ['tenant_id', 'entity_type'], unique=False)
    op.create_table('intel_product_categories',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('hs_code', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['intel_product_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_intel_pc_tenant', 'intel_product_categories', ['tenant_id', 'parent_id'], unique=False)
    op.create_table('price_units',
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('currency', sa.Text(), nullable=False),
    sa.Column('unit', sa.Text(), nullable=False),
    sa.Column('unit_group', sa.Text(), nullable=False),
    sa.Column('applicable_categories', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('product_categories',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('industry_code', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_leaf', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['product_categories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('idx_pc_industry', 'product_categories', ['industry_code'], unique=False)
    op.create_index('idx_pc_parent', 'product_categories', ['parent_id'], unique=False)
    op.create_index('idx_pc_path', 'product_categories', ['path'], unique=False)
    op.create_table('product_specs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('product_category', sa.Text(), nullable=False),
    sa.Column('product_type', sa.Text(), nullable=True),
    sa.Column('wire_diameter', sa.Text(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('mesh_width', sa.Float(), nullable=True),
    sa.Column('mesh_spec', sa.Text(), nullable=True),
    sa.Column('roll_length', sa.Float(), nullable=True),
    sa.Column('bundle_size', sa.Integer(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('spec_hash', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('spec_hash')
    )
    op.create_index('idx_product_specs_category', 'product_specs', ['product_category', 'product_type'], unique=False)
    op.create_table('spec_attributes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('group_code', sa.Text(), nullable=False),
    sa.Column('data_type', sa.Text(), nullable=False),
    sa.Column('unit', sa.Text(), nullable=True),
    sa.Column('unit_group', sa.Text(), nullable=True),
    sa.Column('number_min', sa.Numeric(), nullable=True),
    sa.Column('number_max', sa.Numeric(), nullable=True),
    sa.Column('number_step', sa.Numeric(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scope', sa.Text(), nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('promoted_from', sa.BigInteger(), nullable=True),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sa_group', 'spec_attributes', ['group_code'], unique=False)
    op.create_index('idx_sa_scope_status', 'spec_attributes', ['scope', 'status'], unique=False)
    op.create_table('text_knowledge',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.Column('customer_id', sa.Text(), nullable=True),
    sa.Column('scope', sa.Text(), nullable=False),
    sa.Column('product_category', sa.Text(), nullable=True),
    sa.Column('knowledge_type', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('keywords', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('review_status', sa.Text(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tk_customer', 'text_knowledge', ['tenant_id', 'customer_id', 'status'], unique=False)
    op.create_index('idx_tk_product_category', 'text_knowledge', ['tenant_id', 'product_category', 'status'], unique=False)
    op.create_index('idx_tk_scope', 'text_knowledge', ['scope', 'status'], unique=False)
    op.create_index('idx_tk_tenant_type', 'text_knowledge', ['tenant_id', 'knowledge_type', 'status'], unique=False)
    op.create_table('unit_groups',
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('base_unit', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('account_type', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('plan', sa.Text(), nullable=False),
    sa.Column('is_tenant_admin', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_users_account_type', 'users', ['account_type'], unique=False)
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_table('attribute_proposals',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=False),
    sa.Column('group_code', sa.Text(), nullable=False),
    sa.Column('proposed_name', sa.Text(), nullable=False),
    sa.Column('proposed_aliases', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('proposed_unit', sa.Text(), nullable=True),
    sa.Column('proposed_unit_group', sa.Text(), nullable=True),
    sa.Column('proposed_type', sa.Text(), nullable=False),
    sa.Column('sample_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.Column('similar_attribute_id', sa.BigInteger(), nullable=True),
    sa.Column('similarity_score', sa.Numeric(), nullable=True),
    sa.Column('private_attribute_id', sa.BigInteger(), nullable=True),
    sa.Column('recommended_for_promotion', sa.Boolean(), nullable=False),
    sa.Column('recommendation_score', sa.Numeric(), nullable=True),
    sa.Column('recommended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('reviewer', sa.Text(), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('promoted_attribute_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['product_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['private_attribute_id'], ['spec_attributes.id'], ),
    sa.ForeignKeyConstraint(['promoted_attribute_id'], ['spec_attributes.id'], ),
    sa.ForeignKeyConstraint(['similar_attribute_id'], ['spec_attributes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ap_status', 'attribute_proposals', ['status', 'category_id'], unique=False)
    op.create_table('category_attribute_bindings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=False),
    sa.Column('attribute_id', sa.BigInteger(), nullable=False),
    sa.Column('group_code', sa.Text(), nullable=False),
    sa.Column('attr_role', sa.Text(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('default_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('depends_on', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('scope', sa.Text(), nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=True),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attribute_id'], ['spec_attributes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['product_categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cab_cat', 'category_attribute_bindings', ['category_id', 'scope', 'tenant_id'], unique=False)
    op.create_table('channel_links',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.Column('channel', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('scenario', sa.Text(), nullable=True),
    sa.Column('link_token', sa.Text(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_channel_link_customer', 'channel_links', ['customer_id'], unique=False)
    op.create_index('idx_channel_link_token', 'channel_links', ['link_token'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.Column('channel', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_conv_channel', 'conversations', ['channel'], unique=False)
    op.create_index('idx_conv_customer', 'conversations', ['customer_id'], unique=False)
    op.create_table('intel_shipments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.Column('shipper', sa.Text(), nullable=False),
    sa.Column('ship_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('carrier', sa.Text(), nullable=True),
    sa.Column('notify_party', sa.Text(), nullable=True),
    sa.Column('origin_port', sa.Text(), nullable=True),
    sa.Column('origin_country', sa.Text(), nullable=True),
    sa.Column('dest_port', sa.Text(), nullable=True),
    sa.Column('dest_country', sa.Text(), nullable=True),
    sa.Column('consignee', sa.Text(), nullable=False),
    sa.Column('product_desc', sa.Text(), nullable=False),
    sa.Column('product_desc_norm', sa.Text(), nullable=True),
    sa.Column('hs_code', sa.Text(), nullable=True),
    sa.Column('category_id', sa.BigInteger(), nullable=True),
    sa.Column('qty', sa.Numeric(), nullable=True),
    sa.Column('qty_unit', sa.Text(), nullable=True),
    sa.Column('gross_weight_kg', sa.Numeric(), nullable=True),
    sa.Column('net_weight_kg', sa.Numeric(), nullable=True),
    sa.Column('volume_cbm', sa.Numeric(), nullable=True),
    sa.Column('container_no', sa.Text(), nullable=True),
    sa.Column('container_type', sa.Text(), nullable=True),
    sa.Column('bl_no', sa.Text(), nullable=True),
    sa.Column('voyage_no', sa.Text(), nullable=True),
    sa.Column('declared_value', sa.Numeric(), nullable=True),
    sa.Column('currency', sa.Text(), nullable=True),
    sa.Column('marks', sa.Text(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('shipment_type', sa.Text(), nullable=True),
    sa.Column('incoterm', sa.Text(), nullable=True),
    sa.Column('freight_prepaid', sa.Boolean(), nullable=True),
    sa.Column('source_channel', sa.Text(), nullable=False),
    sa.Column('source_ref', sa.Text(), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('shipper_entity_id', sa.BigInteger(), nullable=True),
    sa.Column('consignee_entity_id', sa.BigInteger(), nullable=True),
    sa.Column('notify_entity_id', sa.BigInteger(), nullable=True),
    sa.Column('carrier_entity_id', sa.BigInteger(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['carrier_entity_id'], ['intel_entities.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['intel_product_categories.id'], ),
    sa.ForeignKeyConstraint(['consignee_entity_id'], ['intel_entities.id'], ),
    sa.ForeignKeyConstraint(['notify_entity_id'], ['intel_entities.id'], ),
    sa.ForeignKeyConstraint(['shipper_entity_id'], ['intel_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_intel_shipments_tenant_consignee', 'intel_shipments', ['tenant_id', 'consignee'], unique=False)
    op.create_index('idx_intel_shipments_tenant_date', 'intel_shipments', ['tenant_id', 'ship_date'], unique=False)
    op.create_index('idx_intel_shipments_tenant_dest', 'intel_shipments', ['tenant_id', 'dest_country'], unique=False)
    op.create_index('idx_intel_shipments_tenant_hs', 'intel_shipments', ['tenant_id', 'hs_code'], unique=False)
    op.create_index('idx_intel_shipments_tenant_shipper', 'intel_shipments', ['tenant_id', 'shipper'], unique=False)
    op.create_table('product_skus',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=False),
    sa.Column('spec_values', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('spec_hash', sa.Text(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('weight_kg', sa.Numeric(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['product_categories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_psk_lookup', 'product_skus', ['tenant_id', 'category_id', 'is_active'], unique=False)
    op.create_table('spec_attribute_values',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('attribute_id', sa.BigInteger(), nullable=False),
    sa.Column('value_code', sa.Text(), nullable=False),
    sa.Column('value_label', sa.Text(), nullable=False),
    sa.Column('value_number', sa.Numeric(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('scope', sa.Text(), nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attribute_id'], ['spec_attributes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sav_attr', 'spec_attribute_values', ['attribute_id', 'status'], unique=False)
    op.create_table('units',
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('unit_group', sa.Text(), nullable=False),
    sa.Column('to_base_factor', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['unit_group'], ['unit_groups.code'], ),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('usage_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=True),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.Column('channel', sa.Text(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_code', sa.Text(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_usage_events_customer', 'usage_events', ['customer_id'], unique=False)
    op.create_index('idx_usage_events_type', 'usage_events', ['event_type'], unique=False)
    op.create_table('user_customers',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_customers_customer', 'user_customers', ['customer_id'], unique=False)
    op.create_index('idx_user_customers_user', 'user_customers', ['user_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('granted_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_roles_user_tenant', 'user_roles', ['user_id', 'tenant_id'], unique=False)
    op.create_table('wechat_bot_accounts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.Column('bot_name', sa.Text(), nullable=False),
    sa.Column('bot_type', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('bot_token_encrypted', sa.Text(), nullable=True),
    sa.Column('last_get_updates_buf', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_wx_bot_customer', 'wechat_bot_accounts', ['customer_id'], unique=False)
    op.create_index('idx_wx_bot_status', 'wechat_bot_accounts', ['status'], unique=False)
    op.create_index('idx_wx_bot_tenant', 'wechat_bot_accounts', ['tenant_id'], unique=False)
    op.create_table('conversation_messages',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('raw_content', sa.Text(), nullable=True),
    sa.Column('normalized_content', sa.Text(), nullable=True),
    sa.Column('intent', sa.Text(), nullable=True),
    sa.Column('product_category', sa.Text(), nullable=True),
    sa.Column('extracted_params_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('quote_status', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_conv_msg_conv', 'conversation_messages', ['conversation_id'], unique=False)
    op.create_table('product_sku_prices',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('sku_id', sa.BigInteger(), nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.Text(), nullable=False),
    sa.Column('price_unit', sa.Text(), nullable=False),
    sa.Column('min_qty', sa.Numeric(), nullable=True),
    sa.Column('tier_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['price_unit'], ['price_units.code'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['product_skus.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_psp_sku_active', 'product_sku_prices', ['sku_id', 'status', 'effective_from'], unique=False)
    op.create_table('product_sku_revisions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('sku_id', sa.BigInteger(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('spec_values', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('spec_hash', sa.Text(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sku_id'], ['product_skus.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_psr_sku', 'product_sku_revisions', ['sku_id'], unique=False)
    op.create_table('wechat_conversations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.Column('bot_account_id', sa.BigInteger(), nullable=False),
    sa.Column('wechat_session_id', sa.Text(), nullable=False),
    sa.Column('from_user_id', sa.Text(), nullable=False),
    sa.Column('last_context_token_encrypted', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bot_account_id'], ['wechat_bot_accounts.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_wx_conv_bot_account', 'wechat_conversations', ['bot_account_id'], unique=False)
    op.create_index('idx_wx_conv_customer', 'wechat_conversations', ['customer_id'], unique=False)
    op.create_index('idx_wx_conv_from_user', 'wechat_conversations', ['bot_account_id', 'from_user_id'], unique=False)
    op.create_index('idx_wx_conv_session', 'wechat_conversations', ['wechat_session_id'], unique=False)
    op.create_table('wechat_message_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('bot_account_id', sa.BigInteger(), nullable=False),
    sa.Column('wechat_session_id', sa.Text(), nullable=True),
    sa.Column('from_user_id', sa.Text(), nullable=True),
    sa.Column('message_id', sa.Text(), nullable=True),
    sa.Column('direction', sa.Text(), nullable=False),
    sa.Column('message_type', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('error_code', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bot_account_id'], ['wechat_bot_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_wx_msg_event_bot', 'wechat_message_events', ['bot_account_id'], unique=False)
    op.create_index('idx_wx_msg_event_session', 'wechat_message_events', ['wechat_session_id'], unique=False)
    op.create_table('quotations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.Column('customer_id', sa.Text(), nullable=False),
    sa.Column('product_category', sa.Text(), nullable=False),
    sa.Column('product_spec', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('spec_hash', sa.Text(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('currency', sa.Text(), nullable=False),
    sa.Column('unit', sa.Text(), nullable=False),
    sa.Column('discount', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('min_quantity', sa.Integer(), nullable=True),
    sa.Column('effective_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sku_id', sa.BigInteger(), nullable=True),
    sa.Column('price_id', sa.BigInteger(), nullable=True),
    sa.Column('schema_version_v2', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['price_id'], ['product_sku_prices.id'], ),
    sa.ForeignKeyConstraint(['sku_id'], ['product_skus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_quotations_lookup', 'quotations', ['customer_id', 'product_category', 'spec_hash', sa.literal_column('effective_from DESC')], unique=False)
    op.create_index('idx_quotations_tenant', 'quotations', ['tenant_id', 'customer_id'], unique=False)
    op.create_index(op.f('ix_quotations_tenant_id'), 'quotations', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quotations_tenant_id'), table_name='quotations')
    op.drop_index('idx_quotations_tenant', table_name='quotations')
    op.drop_index('idx_quotations_lookup', table_name='quotations')
    op.drop_table('quotations')
    op.drop_index('idx_wx_msg_event_session', table_name='wechat_message_events')
    op.drop_index('idx_wx_msg_event_bot', table_name='wechat_message_events')
    op.drop_table('wechat_message_events')
    op.drop_index('idx_wx_conv_session', table_name='wechat_conversations')
    op.drop_index('idx_wx_conv_from_user', table_name='wechat_conversations')
    op.drop_index('idx_wx_conv_customer', table_name='wechat_conversations')
    op.drop_index('idx_wx_conv_bot_account', table_name='wechat_conversations')
    op.drop_table('wechat_conversations')
    op.drop_index('idx_psr_sku', table_name='product_sku_revisions')
    op.drop_table('product_sku_revisions')
    op.drop_index('idx_psp_sku_active', table_name='product_sku_prices')
    op.drop_table('product_sku_prices')
    op.drop_index('idx_conv_msg_conv', table_name='conversation_messages')
    op.drop_table('conversation_messages')
    op.drop_index('idx_wx_bot_tenant', table_name='wechat_bot_accounts')
    op.drop_index('idx_wx_bot_status', table_name='wechat_bot_accounts')
    op.drop_index('idx_wx_bot_customer', table_name='wechat_bot_accounts')
    op.drop_table('wechat_bot_accounts')
    op.drop_index('idx_user_roles_user_tenant', table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index('idx_user_customers_user', table_name='user_customers')
    op.drop_index('idx_user_customers_customer', table_name='user_customers')
    op.drop_table('user_customers')
    op.drop_index('idx_usage_events_type', table_name='usage_events')
    op.drop_index('idx_usage_events_customer', table_name='usage_events')
    op.drop_table('usage_events')
    op.drop_table('units')
    op.drop_index('idx_sav_attr', table_name='spec_attribute_values')
    op.drop_table('spec_attribute_values')
    op.drop_index('idx_psk_lookup', table_name='product_skus')
    op.drop_table('product_skus')
    op.drop_index('idx_intel_shipments_tenant_shipper', table_name='intel_shipments')
    op.drop_index('idx_intel_shipments_tenant_hs', table_name='intel_shipments')
    op.drop_index('idx_intel_shipments_tenant_dest', table_name='intel_shipments')
    op.drop_index('idx_intel_shipments_tenant_date', table_name='intel_shipments')
    op.drop_index('idx_intel_shipments_tenant_consignee', table_name='intel_shipments')
    op.drop_table('intel_shipments')
    op.drop_index('idx_conv_customer', table_name='conversations')
    op.drop_index('idx_conv_channel', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index('idx_channel_link_token', table_name='channel_links')
    op.drop_index('idx_channel_link_customer', table_name='channel_links')
    op.drop_table('channel_links')
    op.drop_index('idx_cab_cat', table_name='category_attribute_bindings')
    op.drop_table('category_attribute_bindings')
    op.drop_index('idx_ap_status', table_name='attribute_proposals')
    op.drop_table('attribute_proposals')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_index('idx_users_account_type', table_name='users')
    op.drop_table('users')
    op.drop_table('unit_groups')
    op.drop_index('idx_tk_tenant_type', table_name='text_knowledge')
    op.drop_index('idx_tk_scope', table_name='text_knowledge')
    op.drop_index('idx_tk_product_category', table_name='text_knowledge')
    op.drop_index('idx_tk_customer', table_name='text_knowledge')
    op.drop_table('text_knowledge')
    op.drop_index('idx_sa_scope_status', table_name='spec_attributes')
    op.drop_index('idx_sa_group', table_name='spec_attributes')
    op.drop_table('spec_attributes')
    op.drop_index('idx_product_specs_category', table_name='product_specs')
    op.drop_table('product_specs')
    op.drop_index('idx_pc_path', table_name='product_categories')
    op.drop_index('idx_pc_parent', table_name='product_categories')
    op.drop_index('idx_pc_industry', table_name='product_categories')
    op.drop_table('product_categories')
    op.drop_table('price_units')
    op.drop_index('idx_intel_pc_tenant', table_name='intel_product_categories')
    op.drop_table('intel_product_categories')
    op.drop_index('idx_intel_entities_tenant', table_name='intel_entities')
    op.drop_index('idx_intel_entities_name', table_name='intel_entities')
    op.drop_table('intel_entities')
    op.drop_index('idx_it_industry', table_name='industry_templates')
    op.drop_table('industry_templates')
    op.drop_table('events_archive_log')
    op.drop_table('events')
    op.drop_index('idx_customers_tenant', table_name='customers')
    op.drop_index('idx_customers_code', table_name='customers')
    op.drop_table('customers')
    op.drop_index('idx_sale_price_lookup', table_name='customer_sale_price_items')
    op.drop_table('customer_sale_price_items')
    op.drop_index('idx_pricing_profile_lookup', table_name='customer_pricing_profiles')
    op.drop_table('customer_pricing_profiles')
    op.drop_index('idx_freight_lookup', table_name='customer_freight_rates')
    op.drop_table('customer_freight_rates')
    op.drop_index('idx_cost_items_lookup', table_name='customer_cost_items')
    op.drop_table('customer_cost_items')
    op.drop_index(op.f('ix_customer_capabilities_tenant_id'), table_name='customer_capabilities')
    op.drop_index('idx_capabilities_tenant', table_name='customer_capabilities')
    op.drop_index('idx_capabilities_lookup', table_name='customer_capabilities')
    op.drop_table('customer_capabilities')
    # ### end Alembic commands ###
